name: rest_app
recipe: laravel
config:
  webroot: public
  php: 8.1
  via: nginx

services:
  appserver:
    type: php:8.1
  database:
    type: mysql
    creds:
      user: myapp
      password: myapp
      database: myapp

  phpmyadmin:
    type: phpmyadmin
    hosts: database
